### ISSUE TITLE
Codecademy hidden courses

### ISSUE THREAD

**Issue by Vic-ST** [A-J-C/CodecademyGroups#1]
Hey @A-J-C! I created an org which I want to have the list of hidden courses(@CodecademyHiddenCourses). Do you want to join?

**Comment by A-J-C** [comment]
Hey, most of the old courses are going to become completely broken when CC moves everything to the new learning environment. So it might not be worth it :(

**Comment by Vic-ST** [comment]
:fearful: Really? They are going to brake with the other courses? That is really annoying! I learned of my programming skills from hidden courses!

**Comment by A-J-C** [comment]
Yeah likely they will not be accessible when CC drops support. Such a shame
:(

**Comment by Vic-ST** [comment]
Okay. I'll check if the help center knows.....

**Comment by Vic-ST** [comment]
confirmed. :sob:

**Comment by Vic-ST** [comment]
Wait a minute. Unconfirmed! The today almost everything has been updated and look: www.codecademy.com/courses/python-beginner-en-mh49a/0/1

**Comment by A-J-C** [comment]
Hmm fair enough, I was under the impression that the whole framework
supporting old courses is going to be removed soon.

**Comment by Vic-ST** [comment]
that is what I thought to! I beginning to think that maybe we should do something like this.
